document.write('<!DOCTYPE html>');
document.write('<html lang="it">');
document.write('   <head>');
document.write('      <meta charset="UTF-8">');
document.write('      <meta name="viewport" content="width=device-width, initial-scale=1.0">');
document.write('      <meta http-equiv="X-UA-Compatible" content="ie=edge">');
//document.write('      <title>SIN ARC</title>');
document.write('      <link rel="stylesheet" href="assets.css">');
document.write('      <link rel="preconnect" href="https://fonts.googleapis.com">');
document.write('      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>');
document.write('      <link href="https://fonts.googleapis.com/css2?family=Inter+Tight:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">');
document.write('      <!--JQUERY-->');
document.write('      <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>');
document.write('      <script src="https://code.jquery.com/ui/1.13.3/jquery-ui.min.js"></script>');
document.write('      <!--SPLIDE-->');
document.write('      <script src="');
document.write('         https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/js/splide.min.js');
document.write('         "></script>');
document.write('      <link href="');
document.write('         https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/css/splide.min.css');
document.write('         " rel="stylesheet">');
document.write('      <link rel="stylesheet" href="style.css?v=1.1">');
document.write('   </head>');
document.write('   <body>');
document.write('      <section class="topbarcontainer">');
document.write('         <div class="topbar">');
document.write('         <h1><a href="/">Sin<span class="hide">Arch</span></a></h1>');
document.write('         <div id="container" class="icon-menu-container" onclick="onMenuToggle();">');
document.write('            <input type="checkbox" id="checkbox"/>');
document.write('            <div id="icon-container">');
document.write('               <div id="icon" class="icon-menu"></div>');
document.write('            </div>');
document.write('         </div>');
document.write('		 </div>');
document.write('      </section>');
document.write('      <section class="menu" style="display:none">');
document.write('         <ul>');
document.write('            <!--<li><a href="/">Arch</a></li>-->');
document.write('            <li><a href="/">Studio</a></li>');
document.write('            <li><a href="/">Progetti</a></li>');
document.write('            <li><a href="/">Ricerca</a></li>');
document.write('            <li><a href="/">Contatti</a></li>');
document.write('            <li><a href="/">News</a></li>');
document.write('         </ul>');
document.write('      </section>');
document.write('   </body>');
document.write('</html>');